In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv("../Data/Raw/New HR_Attrition_dataset.csv",low_memory=False)
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,50,No,Travel_Rarely,277,Sales,9,4,Marketing,1,1,...,3,79,1,28,1,2,1,0,0,0
1,28,No,Travel_Rarely,1379,Research & Development,13,2,Other,1,2,...,2,80,0,10,3,2,4,3,0,3
2,22,Yes,Travel_Frequently,1263,Research & Development,3,4,Life Sciences,1,3,...,2,80,1,1,5,3,0,0,0,0
3,41,No,Travel_Rarely,447,Research & Development,5,3,Life Sciences,1,4,...,1,80,1,11,3,1,3,2,1,2
4,36,No,Travel_Rarely,759,Research & Development,29,4,Life Sciences,1,5,...,4,80,2,10,3,2,10,9,7,8

Basic inspection or reading of data

In [3]:
df.shape
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 35 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   Age                       100000 non-null  int64
 1   Attrition                 100000 non-null  object
 2   BusinessTravel            100000 non-null  object
 3   DailyRate                 100000 non-null  int64
 4   Department                100000 non-null  object
 5   DistanceFromHome          100000 non-null  int64
 6   Education                 100000 non-null  int64
 7   EducationField            100000 non-null  object
 8   EmployeeCount             100000 non-null  int64
 9   EmployeeNumber            100000 non-null  int64
 10  EnvironmentSatisfaction   100000 non-null  int64
 11  Gender                    100000 non-null  object
 12  HourlyRate                99996 non-null   object
 13  JobInvolvement            100000 non-null  int64
 14  JobLevel                  100000 non-null  int64
 15  JobRole                   100000 non-null  object
 16  JobSatisfaction           100000 non-null  int64
 17  MaritalStatus             100000 non-null  object
 18  MonthlyIncome             100000 non-null  int64
 19  MonthlyRate               100000 non-null  int64
 20  NumCompaniesWorked        100000 non-null  int64
 21  Over18                    100000 non-null  object
 22  OverTime                  100000 non-null  object
 23  PercentSalaryHike         100000 non-null  int64
 24  PerformanceRating         100000 non-null  int64
 25  RelationshipSatisfaction  100000 non-null  int64
 26  StandardHours             100000 non-null  int64
 27  StockOptionLevel          100000 non-null  int64
 28  TotalWorkingYears         100000 non-null  int64
 29  TrainingTimesLastYear     100000 non-null  int64
 30  WorkLifeBalance           100000 non-null  int64
 31  YearsAtCompany            100000 non-null  int64
 32  YearsInCurrentRole        100000 non-null  int64
 33  YearsSinceLastPromotion   100000 non-null  int64
 34  YearsWithCurrManager      100000 non-null  int64
dtypes: int64(25), object(10)
memory usage: 26.7+ MB

checking missing values

In [4]:
df.isnull().sum()

Age                         0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  4
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64

In [5]:
print(df['HourlyRate'].isnull().sum())
df['HourlyRate'].describe()

4

count     99996
unique       75
top          66
freq       1795
Name: HourlyRate, dtype: object

In [6]:
df['HourlyRate']=pd.to_numeric(df['HourlyRate'],errors='coerce')

In [7]:
df['HourlyRate'].isnull().sum()
df['HourlyRate'].describe()

count    99995.000000
mean        65.914956
std         20.306611
min         29.000000
25%         48.000000
50%         66.000000
75%         84.000000
max        102.000000
Name: HourlyRate, dtype: float64

In [8]:
#filling the missing value
df['HourlyRate'].fillna(df['HourlyRate'].median(),inplace=True)

C:\Users\alok\AppData\Local\Temp\ipykernel_18376\1498901471.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['HourlyRate'].fillna(df['HourlyRate'].median(),inplace=True)

In [9]:
print(df.duplicated().sum())
df.drop_duplicates(inplace=True)

0

In [10]:
#feature engineering
df['AnnualIncome']=df['MonthlyIncome']*12
# print(df['AnnualIncome'])

In [11]:
df['Attritionsign']=df['Attrition'].map({'Yes':1,'No':0})

In [12]:
df['overtimedone']=df['OverTime'].map({'Yes':1,'No':0})

In [13]:
bins=[18,25,35,45,55,65]
labels=["18-25","26-35","36-45","46-55","56-65"]
df["age_group"]=pd.cut(df["Age"],
                       bins=bins,
                       labels=labels)

Save the cleaned Dataset

In [15]:
df.to_csv("../Data/Cleaned/hr_cleaned.csv",index=False)

In [16]:
df.shape
df.duplicated().sum()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 39 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   Age                       100000 non-null  int64
 1   Attrition                 100000 non-null  object
 2   BusinessTravel            100000 non-null  object
 3   DailyRate                 100000 non-null  int64
 4   Department                100000 non-null  object
 5   DistanceFromHome          100000 non-null  int64
 6   Education                 100000 non-null  int64
 7   EducationField            100000 non-null  object
 8   EmployeeCount             100000 non-null  int64
 9   EmployeeNumber            100000 non-null  int64
 10  EnvironmentSatisfaction   100000 non-null  int64
 11  Gender                    100000 non-null  object
 12  HourlyRate                100000 non-null  float64
 13  JobInvolvement            100000 non-null  int64
 14  JobLevel                  100000 non-null  int64
 15  JobRole                   100000 non-null  object
 16  JobSatisfaction           100000 non-null  int64
 17  MaritalStatus             100000 non-null  object
 18  MonthlyIncome             100000 non-null  int64
 19  MonthlyRate               100000 non-null  int64
 20  NumCompaniesWorked        100000 non-null  int64
 21  Over18                    100000 non-null  object
 22  OverTime                  100000 non-null  object
 23  PercentSalaryHike         100000 non-null  int64
 24  PerformanceRating         100000 non-null  int64
 25  RelationshipSatisfaction  100000 non-null  int64
 26  StandardHours             100000 non-null  int64
 27  StockOptionLevel          100000 non-null  int64
 28  TotalWorkingYears         100000 non-null  int64
 29  TrainingTimesLastYear     100000 non-null  int64
 30  WorkLifeBalance           100000 non-null  int64
 31  YearsAtCompany            100000 non-null  int64
 32  YearsInCurrentRole        100000 non-null  int64
 33  YearsSinceLastPromotion   100000 non-null  int64
 34  YearsWithCurrManager      100000 non-null  int64
 35  AnnualIncome              100000 non-null  int64
 36  Attritionsign             100000 non-null  int64
 37  overtimedone              100000 non-null  int64
 38  age_group                 99469 non-null   category
dtypes: category(1), float64(1), int64(28), object(9)
memory usage: 29.1+ MB

In [17]:
missing_df=pd.DataFrame({'MissingValues':df.isnull().sum(),
                         'Percentage':(df.isnull().sum()/len(df))*100})
missing_df[missing_df['MissingValues']>0]

           MissingValues  Percentage
age_group            531       0.531

In [18]:
bins=[0,25,35,45,55,100]
labels=["18-25","26-35","36-45","46-55","56+"]
df["age_group"]=pd.cut(df["Age"],
                       bins=bins,
                       labels=labels)

In [19]:
df['age_group'].isnull().sum()

np.int64(0)

In [20]:
df[['OverTime','overtimedone']].head(20)

   OverTime  overtimedone
0       Yes             1
1       Yes             1
2       Yes             1
3        No             0
4        No             0
5       Yes             1
6        No             0
7        No             0
8        No             0
9        No             0
10       No             0
11       No             0
12      Yes             1
13      Yes             1
14       No             0
15       No             0
16      Yes             1
17       No             0
18      Yes             1
19       No             0

In [21]:
df['overtimedone']=df['OverTime'].map({'Yes':1,'No':0})

In [22]:
df['overtimedone'].isnull().sum()

np.int64(0)

In [23]:
missing_df=pd.DataFrame({'MissingValues':df.isnull().sum(),
                         'Percentage':(df.isnull().sum()/len(df))*100})
missing_df[missing_df['MissingValues']>0]

Empty DataFrame
Columns: [MissingValues, Percentage]
Index: []

In [24]:
df.to_csv("../Data/Cleaned/hr_cleaned.csv",index=False)

Data Cleaning Summary:

1. Checked missing values.
2. Fixed HourlyRate missing values using median.
3. Converted HourlyRate into numeric format.
4. Created age_group feature.
5. Fixed OverTime mapping into overtimedone column.
6. Verified that no missing values remain.
7. Saved the cleaned dataset as hr_cleaned.csv.